### 1. Create shortcut for url from text/plain body
POST {{server_address}}
Content-Type: text/plain; charset=UTF-8

https://lengthy-url-1.com/

### 2. Create shortcut for url from application/json body
POST {{server_address}}/api/shorten
Content-Type: application/json

{
  "url": "https://lengthy-url-2.com/"
}

### 3. Create shortcut for url from application/gzip body
POST {{server_address}}
Content-Type: application/gzip
Content-Encoding: gzip

< ./compressed_request.gz

### 4. Create shortcuts for urls batch from application/json body
POST {{server_address}}/api/shorten/batch
Content-Type: application/json

[
  {
    "correlation_id": "056d98a6-f001-4526-b5d9-071900d57363",
    "original_url": "https://lengthy-url-4.com/"
  },
  {
    "correlation_id": "6c9fa3c4-469c-4541-a636-66b7f8b5cbe2",
    "original_url": "https://lengthy-url-5.com/"
  }
]

### 5. Get origin url from shortcut
# @no-redirect
GET {{server_address}}/1

### 6. Get urls created by current user
GET {{server_address}}/api/user/urls

### 7. Remove urls created by current user
DELETE {{server_address}}/api/user/urls
Content-Type: application/json

[
  "1",
  "3"
]

### 8. Check connection to database
GET {{server_address}}/ping/



### 9. Create shortcut for url
GRPC {{grpc_server_address}}/urlService.URLService/ShortenURL

{
  "url": "https://lengthy-url-1.com/"
}

### 10. Create shortcuts for urls batch
GRPC {{grpc_server_address}}/urlService.URLService/ShortenURLsBatch

{
  "request": [
    {
      "correlation_id": "056d98a6-f001-4526-b5d9-071900d57363",
      "original_url": "https://lengthy-url-2.com/"
    },
    {
      "correlation_id": "6c9fa3c4-469c-4541-a636-66b7f8b5cbe2",
      "original_url": "https://lengthy-url-3.com/"
    }
  ]
}

### 11. Get origin url from shortcut
GRPC {{grpc_server_address}}/urlService.URLService/GetOriginalURL
# need metadata for proper work
# https://youtrack.jetbrains.com/issue/IDEA-290485

{
  "id": "1"
}

### 12. Get urls created by current user
GRPC {{grpc_server_address}}/urlService.URLService/GetUsersURLs
# need metadata for proper work

### 13. Remove urls created by current user
GRPC 127.0.0.1:50051/urlService.URLService/DeleteUserURLs
# need metadata for proper work

{
  "ids": [
    "1",
    "3"
  ]
}



### 14. Create shortcut for url
POST {{server_address}}/gw/shorten
Content-Type: application/json

{
  "url": "https://lengthy-url-1.com/"
}

### 15. Create shortcuts for urls batch
POST {{server_address}}/gw/shorten/batch
Content-Type: application/json

{
  "request": [
    {
      "correlation_id": "056d98a6-f001-4526-b5d9-071900d57363",
      "original_url": "https://lengthy-url-2.com/"
    },
    {
      "correlation_id": "6c9fa3c4-469c-4541-a636-66b7f8b5cbe2",
      "original_url": "https://lengthy-url-3.com/"
    }
  ]
}

### 16. Get origin url from shortcut
# @no-redirect
GET {{server_address}}/gw/11

### 17. Get urls created by current user
GET {{server_address}}/gw/user/urls

### 18. Remove urls created by current user
DELETE {{server_address}}/gw/user/urls
Content-Type: application/json

{
  "ids": [
    "1",
    "3"
  ]
}